In [1]:
import numpy as np

In [3]:
a = np.array([12, 34, 67])

In [4]:
a.shape

(3,)

In [5]:
a.size

3

In [6]:
a.dtype

dtype('int64')

In [7]:
b = np.array([12, 34, 67], dtype=np.int8)

In [8]:
b.dtype

dtype('int8')

In [10]:
c = np.array([[11, 12], [22, 23]])

In [11]:
c

array([[11, 12],
       [22, 23]])

In [13]:
c.shape

(2, 2)

In [14]:
c.size

4

In [15]:
d = np.array([[11, 12], [22, 23, 24]])

In [16]:
d

array([list([11, 12]), list([22, 23, 24])], dtype=object)

In [17]:
d.shape

(2,)

In [22]:
d = np.array([[[[[1]]]], [[[[1]]]]])

In [23]:
d.shape

(2, 1, 1, 1, 1)

In [24]:
[[12, 13, 14], [12, 13, 14]]

[[12, 13, 14], [12, 13, 14]]

In [25]:
e = np.array([[[11], [12], [13]], [[11], [12], [13]]])

In [26]:
e.shape

(2, 3, 1)

In [27]:
np.array(range(100))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [31]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [32]:
first = np.arange(12)

In [33]:
first

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
second = first.reshape(4, 3)

In [35]:
second

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
third = first.reshape(3, 1, 2, 1, 2)

In [37]:
third

array([[[[[ 0,  1]],

         [[ 2,  3]]]],



       [[[[ 4,  5]],

         [[ 6,  7]]]],



       [[[[ 8,  9]],

         [[10, 11]]]]])

In [38]:
third.ndim

5

In [39]:
first

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
second

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
first[0] = 1000

In [42]:
second

array([[1000,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8],
       [   9,   10,   11]])

In [43]:
first.dtype

dtype('int64')

In [45]:
fourth = first.astype(float)

In [52]:
np.zeros((10, 10), dtype=np.int8)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [53]:
np.ones((10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [55]:
np.full((5, 5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])