In [1]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_regression

In [2]:
bias = 100
X, y = make_regression(n_samples=1000, n_features=4, bias=bias, noise=10, random_state=42)

In [11]:
class CustomCloseLinearReg:
    
    def fit(self, X, y):
        
        X = np.hstack([np.ones([X.shape[0], 1]), X])
        y = y.reshape(-1, 1)
        
        first = np.linalg.inv(np.dot(X.T, X))
        second = np.dot(X.T, y)
        
        self.theta_ = np.dot(first, second)
    
    def predict(self, X):
        X = np.hstack([np.ones([X.shape[0], 1]), X])
        return np.dot(X, self.theta_)

In [12]:
model = CustomCloseLinearReg()

In [13]:
model.fit(X, y)

In [15]:
model.predict(X[:10])

array([[ 94.85255944],
       [ 50.34423332],
       [-30.07314717],
       [107.3453379 ],
       [-34.40987675],
       [143.55941103],
       [ 98.29972569],
       [ 67.75313807],
       [-58.48364998],
       [128.84465   ]])

In [16]:
y[:10]

array([ 91.42452817,  67.27652907, -21.41679852, 107.65226614,
       -33.47206507, 134.70114338,  89.51540077,  69.58301091,
       -64.36203085, 137.59692238])

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
m2 = LinearRegression()

In [19]:
m2.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [21]:
m2.predict(X[:10])

array([ 94.85255944,  50.34423332, -30.07314717, 107.3453379 ,
       -34.40987675, 143.55941103,  98.29972569,  67.75313807,
       -58.48364998, 128.84465   ])

In [26]:
from sklearn.datasets import load_boston

In [27]:
X, y = load_boston(return_X_y=True)

In [30]:
model.fit(X, y)

model.predict(X[:5])

array([[30.00821269],
       [25.0298606 ],
       [30.5702317 ],
       [28.60814055],
       [27.94288232]])

In [31]:
m2.fit(X, y)
m2.predict(X[:5])

array([30.00821269, 25.0298606 , 30.5702317 , 28.60814055, 27.94288232])

In [32]:
X.shape

(506, 13)