In [1]:
import numpy as np

In [2]:
a = np.arange(25).reshape(5, 5)

In [7]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
b

array([[0, 1],
       [5, 6]])

In [9]:
b[:, :] = 0

In [10]:
a

array([[ 0,  0,  2,  3,  4],
       [ 0,  0,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
li = [2, 55, 8, 0]

In [18]:
c = np.array(li, dtype=str)

In [19]:
c

array(['2', '55', '8', '0'], dtype='<U2')

In [22]:
np.full((4, 5), 44)

array([[44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44],
       [44, 44, 44, 44, 44]])

In [24]:
# np.empty((4, 5))

In [25]:
a = np.arange(10, 20)
b = np.arange(1, 11)

In [26]:
a ** b

array([           10,           121,          1728,         28561,
              537824,      11390625,     268435456,    6975757441,
        198359290368, 6131066257801])

In [27]:
a = np.arange(20).reshape(4, 5)

In [28]:
b = np.arange(5)

In [29]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [30]:
b

array([0, 1, 2, 3, 4])

In [32]:
a.shape, b.shape

((4, 5), (5,))

In [33]:
b + a

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18],
       [15, 17, 19, 21, 23]])

In [34]:
a = np.random.random((2,3))

In [35]:
a

array([[0.25662228, 0.73201905, 0.94994689],
       [0.00121501, 0.19210832, 0.60090495]])

In [36]:
a.sum()

2.732816495602562

In [40]:
a.sum(axis=0, keepdims=True)

array([[0.25783729, 0.92412737, 1.55085184]])

In [47]:
np.prod([[2, 5], [6, 8]], axis=1, keepdims=True)


array([[10],
       [48]])

In [48]:
a 

array([[0.25662228, 0.73201905, 0.94994689],
       [0.00121501, 0.19210832, 0.60090495]])

In [49]:
b = a.flatten()

In [50]:
b[0] = 66

In [51]:
a

array([[0.25662228, 0.73201905, 0.94994689],
       [0.00121501, 0.19210832, 0.60090495]])

In [53]:
c = a.ravel()

In [54]:
c

array([0.25662228, 0.73201905, 0.94994689, 0.00121501, 0.19210832,
       0.60090495])

In [55]:
c[0] = 90

In [56]:
a

array([[9.00000000e+01, 7.32019054e-01, 9.49946886e-01],
       [1.21500591e-03, 1.92108315e-01, 6.00904954e-01]])

In [70]:
arr = np.random.randint(0, 1000, (10, 5))

In [71]:
arr

array([[498, 355, 890, 319, 498],
       [155, 921, 136, 181, 793],
       [760, 164, 975, 791,  72],
       [ 33, 525,  97, 541, 382],
       [691, 934, 900, 327, 465],
       [508, 807, 137, 273, 246],
       [791, 688,  79, 603, 258],
       [313, 965, 648, 858, 743],
       [406, 372, 429, 782, 478],
       [479,  33,  83, 783, 629]])

In [78]:
list(arr.argmax(axis=1))

[2, 1, 2, 3, 1, 1, 0, 1, 3, 3]

In [79]:
[list(item) for item in arr]

[[498, 355, 890, 319, 498],
 [155, 921, 136, 181, 793],
 [760, 164, 975, 791, 72],
 [33, 525, 97, 541, 382],
 [691, 934, 900, 327, 465],
 [508, 807, 137, 273, 246],
 [791, 688, 79, 603, 258],
 [313, 965, 648, 858, 743],
 [406, 372, 429, 782, 478],
 [479, 33, 83, 783, 629]]